### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by marcin-wosinek** [8bitDesigner/ng-fastclick#1]
Thanks for wrapping fastclick for angular apps!

How this module is approaching to using original code? 
There is fastclick dependency defined in bower.json & README says:

> This is a very thin (3 line!) Angular wrapper around the FT's fantastic FastClick

This make impression that those two modules should be included to html separately. Jet all FastClick is included already in index.js file; so the dependency loaded by bower can't even be use.

**Comment by 8bitDesigner** [comment]
You are 100% totally correct, thanks for catching that! I've removed the dependency in [bf4b094](https://github.com/8bitDesigner/ng-fastclick/commit/bf4b094bd45b6675330a68e5ba350f24bf10350f)
