### ISSUE TITLE
Add fastclick dependency to your bower.json file.

### ISSUE THREAD

**Issue by mez** [8bitDesigner/ng-fastclick#4]
This would pull down that file along with this install and save a step!

Thanks for this wrapper!

**Comment by 8bitDesigner** [comment]
Thanks, mate! If you're using the latest version ([v1.0.1](https://github.com/8bitDesigner/ng-fastclick/tree/v1.0.1) and either [`dist/index.js`](https://github.com/8bitDesigner/ng-fastclick/blob/v1.0.1/dist/index.js) or [`dist/index.min.js`](https://github.com/8bitDesigner/ng-fastclick/blob/v1.0.1/dist/index.min.js) you get the whole sheebang at once; no need for a separate file.

**Comment by 8bitDesigner** [comment]
(But I go back and forth on how to package this, so I may change my mind in the future and include the thing as two separate files and a Bower dependency)
